/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { LigneDeVente } from "./LigneDeVente";
import { LigneDeVenteCountArgs } from "./LigneDeVenteCountArgs";
import { LigneDeVenteFindManyArgs } from "./LigneDeVenteFindManyArgs";
import { LigneDeVenteFindUniqueArgs } from "./LigneDeVenteFindUniqueArgs";
import { DeleteLigneDeVenteArgs } from "./DeleteLigneDeVenteArgs";
import { LigneDeVenteService } from "../ligneDeVente.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => LigneDeVente)
export class LigneDeVenteResolverBase {
  constructor(
    protected readonly service: LigneDeVenteService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "LigneDeVente",
    action: "read",
    possession: "any",
  })
  async _ligneDeVentesMeta(
    @graphql.Args() args: LigneDeVenteCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [LigneDeVente])
  @nestAccessControl.UseRoles({
    resource: "LigneDeVente",
    action: "read",
    possession: "any",
  })
  async ligneDeVentes(
    @graphql.Args() args: LigneDeVenteFindManyArgs
  ): Promise<LigneDeVente[]> {
    return this.service.ligneDeVentes(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => LigneDeVente, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "LigneDeVente",
    action: "read",
    possession: "own",
  })
  async ligneDeVente(
    @graphql.Args() args: LigneDeVenteFindUniqueArgs
  ): Promise<LigneDeVente | null> {
    const result = await this.service.ligneDeVente(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => LigneDeVente)
  @nestAccessControl.UseRoles({
    resource: "LigneDeVente",
    action: "delete",
    possession: "any",
  })
  async deleteLigneDeVente(
    @graphql.Args() args: DeleteLigneDeVenteArgs
  ): Promise<LigneDeVente | null> {
    try {
      return await this.service.deleteLigneDeVente(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
