/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Produit as PrismaProduit } from "@prisma/client";

export class ProduitServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.ProduitCountArgs, "select">): Promise<number> {
    return this.prisma.produit.count(args);
  }

  async produits(args: Prisma.ProduitFindManyArgs): Promise<PrismaProduit[]> {
    return this.prisma.produit.findMany(args);
  }
  async produit(
    args: Prisma.ProduitFindUniqueArgs
  ): Promise<PrismaProduit | null> {
    return this.prisma.produit.findUnique(args);
  }
  async createProduit(args: Prisma.ProduitCreateArgs): Promise<PrismaProduit> {
    return this.prisma.produit.create(args);
  }
  async updateProduit(args: Prisma.ProduitUpdateArgs): Promise<PrismaProduit> {
    return this.prisma.produit.update(args);
  }
  async deleteProduit(args: Prisma.ProduitDeleteArgs): Promise<PrismaProduit> {
    return this.prisma.produit.delete(args);
  }
}
